# Generic functions that GUI classes can attach to

# convenience for interacting with the module
setGeneric("getWidget", function(gui, module, id) standardGeneric("getWidget"))
setGeneric("setWidgets", function(gui, module, ...) standardGeneric("setWidgets"))
setGeneric("getSetting", function(gui, module, id) standardGeneric("getSetting"))

# making the gui
setGeneric("makeGUI", function(gui, module) standardGeneric("makeGUI"))
setGeneric("destroyGUI", function(gui, module) standardGeneric("destroyGUI"))
setGeneric("remakeGUI", function(gui, module, show = TRUE) standardGeneric("remakeGUI"))
setGeneric("showGUI", function(gui, module) standardGeneric("showGUI"))
setGeneric("hideGUI", function(gui, module) standardGeneric("hideGUI"))

# specific functions streamlining GUI design but that are not intended to be derived
setGeneric("getNavigationXML", function(gui, module) standardGeneric("getNavigationXML"))
setGeneric("makeNavigation", function(gui, module) standardGeneric("makeNavigation"))
setGeneric("makeInfoBar", function(gui, module) standardGeneric("makeInfoBar"))

# getting and setting key widgets
setGeneric("getWindow", function(gui, module) standardGeneric("getWindow"))
setGeneric("getWinGroup", function(gui, module) standardGeneric("getWinGroup"))
setGeneric("setMenuGroup", function(gui, module, menuGroup) standardGeneric("setMenuGroup"))
setGeneric("setToolbarGroup", function(gui, module, toolbarGroup) standardGeneric("setToolbarGroup"))

# functions that are intended to be extended in GUI derived classes
setGeneric("getMenuXML", function(gui, module) standardGeneric("getMenuXML"))
setGeneric("getToolbarXML", function(gui, module) standardGeneric("getToolbarXML"))
setGeneric("makeMainGUI", function(gui, module) standardGeneric("makeMainGUI"))
setGeneric("setNavigationActions", function(gui, module, actionGrp) standardGeneric("setNavigationActions"))

# other utility functions for interacting with the GUI
setGeneric("showInfo", function(gui, module, msg, type="question", timer=2, okButton=TRUE) standardGeneric("showInfo"))
setGeneric("hideInfo", function(gui, module) standardGeneric("hideInfo"))

#########
# Class #
#########

# S4 class GUI
GUI <- setClass("BaseGUI", representation = list(module="character")) # which module this belongs to, is automatically set by the module

setMethod("initialize", "BaseGUI", function(.Object, ...) {
  callNextMethod(.Object, ...)
})

###################
# general Methods #
###################

setMethod("makeGUI", "BaseGUI", function(gui, module) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am making my GUI.\n")
  options("guiToolkit"="RGtk2") # everything is written in RGtk2
  
  # make window
  win <- gwindow(
    getSetting(gui, module, "windowTitle"), visible=FALSE, 
    width=getSetting(gui, module, "windowSize")[1], 
    height=getSetting(gui, module, "windowSize")[2])
  
  # destroy window properly
  addHandlerDestroy(win, function(h,...) {
      cat(paste0("Window for ", class(gui), " (module ", gui@module,") is being destroyed! Cleaning all widgets in the module.\n"))
      module$cleanWidgets() # clean all widget references
    }) # clean widgets
  
  # save window in module
  setWidgets(gui, module, window = win)
  
  # top window group
  baseGroup <- ggroup(horizontal=FALSE, expand=TRUE, cont = win, spacing=0) # contains only the winGroup and the infobar
  parent <- getToolkitWidget(baseGroup)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border
  setWidgets(gui, module, 
    baseGroup = baseGroup,
    winGroup = ggroup(horizontal=FALSE, expand=TRUE, cont = baseGroup, spacing=0))
  
  # make info bar
  makeInfoBar(gui, module)
  
  # main make GUI
  makeMainGUI(gui, module)
  makeNavigation(gui, module)
})

setMethod("destroyGUI", "BaseGUI", function(gui, module) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am destroying my GUI.\n")
  dispose(getWindow(gui, module)) # destroy window
  module$cleanWidgets() # clean all widget references
})

setMethod("remakeGUI", "BaseGUI", function(gui, module, show = TRUE) {
  destroyGUI(gui, module)
  makeGUI(gui, module)
  if (show)
    showGUI(gui, module)
})

setMethod("showGUI", "BaseGUI", function(gui, module) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am showing my GUI.\n")
  if (is.null(getWindow(gui, module)))
    makeGUI(gui, module)
  visible(getWindow(gui, module), TRUE)
})

setMethod("hideGUI", "BaseGUI", function(gui, module) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am hiding my GUI.\n")
  if (!is.null(getWindow(gui, module)))
    visible(getWindow(gui, module), FALSE)
})

################################
# methods for streamlining GUI #
################################

setMethod("getNavigationXML", "BaseGUI", function(gui, module) {
  return(paste(
    '<ui>',
      '<menubar name="menubar">',
        getMenuXML(gui, module),      
      '</menubar>',
      '<toolbar name ="toolbar">',
        getToolbarXML(gui, module),
      '</toolbar>',
    '</ui>', sep="\n"))
})

setMethod("makeNavigation", "BaseGUI", function(gui, module) {
  
  # navigation actions
  cat("\tInitializing Navigation.\n")
  setWidgets(gui, module, actionGroup = gtkActionGroup ("FileGroup"))
  cat("\tSetting Navigation Actions.\n")
  setNavigationActions(gui, module, getWidget(gui, module, 'actionGroup'))
  
  # UI manager for navigation
  cat("\tMaking Navigation Manager.\n")
  uimanager <- gtkUIManagerNew() # ui manager
  uimanager$insertActionGroup (getWidget(gui, module, 'actionGroup'), 0) # add actions
  uimanager$addUiFromString (getNavigationXML(gui, module)) # add ui 
  
  # menu
  menuGrp <- getWidget(gui, module, 'menuGroup')
  if (!is.null(menuGrp)) {
    cat("\tMaking Menubar.\n")
    getToolkitWidget(menuGrp)$packStart (uimanager$getWidget ("/menubar"), FALSE ) # add menu
  }
    
  # toolbar
  toolbarGrp <- getWidget(gui, module, 'toolbarGroup')
  if (!is.null(toolbarGrp)) {
    getToolkitWidget(toolbarGrp)$packStart (uimanager$getWidget ( "/toolbar" ), FALSE) # add toolbar
    cat("\tMaking Toolbar.\n")
  }
  getToolkitWidget(getWindow(gui, module))$addAccelGroup (uimanager$getAccelGroup()) # add keyboard triggers
  
})

setMethod("makeInfoBar", "BaseGUI", function(gui, module){
  infoBar <- gtkInfoBar (show=FALSE) 
  infoBar$setNoShowAll(TRUE)
  infoLabel <- gtkLabel ( "Warning , Warning")
  infoBar$setMessageType("question") 
  infoBar$getContentArea()$add(infoLabel)
  infoOkButton <- infoBar$addButton(button.text = "gtk-ok", response.id = GtkResponseType['ok'])
  gSignalConnect(infoBar, "response", function(infoBar, resp.id) hideInfo(gui, module))
  getToolkitWidget(getWidget(gui, module, "baseGroup"))$packStart(infoBar, expand=FALSE)
  setWidgets(gui, module, infoBar = infoBar, infoLabel = infoLabel, infoOkButton = infoOkButton)
})


#' show an info message
#' type - styling of the mssage, info, error, question, warning are the standard ones
#' timer - time in seconds until message disappears automatically
#' okButton - whether there is an ok button or not
setMethod("showInfo", "BaseGUI", function(gui, module, msg, type="question", timer=2, okButton=TRUE) {
  cat("\tShowing info message for", timer, "seconds.\n")
  getWidget(gui, module, 'infoBar')$setMessageType(type)
  getWidget(gui, module, 'infoLabel')$setText(msg)
  getWidget(gui, module, 'infoBar')$show()
  if (!okButton)
    getWidget(gui, module, 'infoOkButton')$hide()  
  else
    getWidget(gui, module, 'infoOkButton')$show()
  if (!is.null(timer)) {
    Sys.sleep(timer)
    hideInfo(gui, module)
   }
})

# hide info bar
setMethod("hideInfo", "BaseGUI", function(gui, module) {
  cat("\tHiding info message.\n")
  getWidget(gui, module, 'infoBar')$hide()
})


############################################
# methods that are supposed to be extended #
############################################

setMethod("getMenuXML", "BaseGUI", function(gui, module) { return('') })

setMethod("getToolbarXML", "BaseGUI", function(gui, module) { return('') })

setMethod("makeMainGUI", "BaseGUI", function(gui, module) {})

setMethod("setNavigationActions", "BaseGUI", function(gui, module, actionGrp) { })

######################################################
# Convenience functions for interacting with the module #
######################################################

setMethod("getWidget", "BaseGUI", function(gui, module, id) {
  return(module$getWidget(id))
})

setMethod("setWidgets", "BaseGUI", function(gui, module, ...) {
  return(module$setWidgets(...))
})

setMethod("getSetting", "BaseGUI", function(gui, module, id) {
  return(module$getSetting(id))
})

#FIXME: implement setSettings!

###################################
# Getting and Setting key widgets #
###################################

setMethod("getWindow", "BaseGUI", function(gui, module) {
  return(getWidget(gui, module, "window"))
})

setMethod("getWinGroup", "BaseGUI", function(gui, module) {
  return(getWidget(gui, module, "winGroup"))
})

setMethod("setMenuGroup", "BaseGUI", function(gui, module, menuGroup) {
  setWidgets(gui, module, menuGroup = menuGroup)
})

setMethod("setToolbarGroup", "BaseGUI", function(gui, module, toolbarGroup) {
  setWidgets(gui, module, toolbarGroup = toolbarGroup)
})
